server:
   port: 8771

spring:
   application:
      name: gateway-service
   cloud:
     gateway:
      routes:
         - id: twitter-service
           uri: 'http://localhost:8200'
           predicates:
            - Path=/rest/api/tweets/**
         - id: instagram-service
           uri: 'http://localhost:8201'
           predicates:
            - Path=/rest/api/instagram/posts/**
         - id: facebook-service
           uri: 'http://localhost:8202'
           predicates:
            - Path=/rest/api/facebook/posts/**